# Generated by Django 4.2.23 on 2025-06-17 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.TextField(default='F->G-F-G, G->F+G+F')),
                ('axiom', models.CharField(default='F', max_length=1)),
                ('iterations', models.IntegerField(default=4)),
                ('segment_length', models.IntegerField(default=3)),
                ('initial_heading', models.IntegerField(default=90)),
                ('angle_increment', models.IntegerField(default=60)),
                ('thickness', models.IntegerField(default=3)),
                ('color', models.TextField(default='#000000')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
