# Generated by Django 5.2.3 on 2025-06-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemparameters',
            name='axiom',
            field=models.CharField(default='F', max_length=20),
        ),
    ]
